name: 'alexmogi helloworld release'
repository:
  url: https://github.com/alex1545/helloworld
  poll_interval: "1m"
  branch_filter: ['master']

pipeline:
  stages:
  - stage: Build and Release helloworld
    type: GCB
    filename: /louhi-config/helloworld/gcb/release.yaml
    artifacts:
      src: 'go/src/helloworld'
      out:
        docker-images: 'helloworld'

notifications:
- type: Email
  to: ["alexmogi@google.com"]
  subject: '%{FLOW.NAME}: %{FLOW.BRANCH} rev:%{OPERATION.REVISION}'
  message: |
    The current status is %{OPERATION.STATUS}.
    See details in %{OPERATION.LINK}
  conditions:
    - event_source: pipeline
      status: [SUCCESS, FAILURE, ERROR]
